### ISSUE TITLE
Support the same browsers as OpenTok.js

### ISSUE THREAD

**Issue by aiham** [wobbals/opentok-mos-estimator#1]
The only newer ES6 features I see in use are `const` [1] and `let` [2]. If `var` is used instead then you can automatically support the same browsers that OpenTok.js supports [3]. I'm happy to submit a PR if that's what you want.

If you only care about evergreen browsers then if I were you I'd go all out and use arrow functions and other nice syntax sugar that comes with ES6.

[1] http://caniuse.com/#feat=const
[2] http://caniuse.com/#feat=let
[3] https://support.tokbox.com/hc/en-us/articles/202884234-What-browsers-does-OpenTok-support-

**Comment by wobbals** [comment]
Good shout, thanks Aiham. Probably this module is simple enough for now, I'll go ahead and stick with `var`. PRs always welcome 😄

**Comment by aiham** [comment]
Oh you did it, that was fast. Was just about to submit that PR :P
